import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headers from "@/Component/layout/header";
import Footer from "@/Component/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
      <body className="w-full">
        <Headers />
        {children}
        <Footer />
      </body>
    </html>
  );
}
